services:
  php:
    build:
      context: .
    volumes:
      - ./src:/var/www/html

  web:
    image: nginx:stable-alpine3.23-perl
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - .docker/nginx/nginx_template_local.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"

  node:
    image: node:lts-alpine3.22
    user: "1000:1000"
    working_dir: /assets
    volumes:
      - ./src:/assets
    command: sh -c "npm install && npm run build"

  db:
    image: mariadb:12.2.2
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:8.2.4-alpine3.22
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
